notifications:
  email: false

language: python

env:
    - NOPLOT=1

matrix:
    include:
        - os: linux
          sudo: false
          python: 2.7
        - os: linux
          sudo: false
          python: 3.6
        - os: osx
          language: generic

install:
  - pip install pytest numpy
  - python setup.py bdist_wheel
  - pip install --pre --no-index --find-links dist/ ad3

script:
  - echo "Running tests"
  - mkdir empty_folder; cd empty_folder; pytest -vs --pyargs ad3; cd ..
  - echo "Running examples"
  - for f in examples/python/*.py; do echo $f; python $f; done
